import pandas as pd
import matplotlib.pyplot as plt

# Read the Monitor log
df = pd.read_csv("training_logs/monitor.csv", skiprows=1)
# (skiprows=1 ignores SB3’s comment line)

# Each row corresponds to an episode
episodes = range(1, len(df["r"]) + 1)
#rewards = df["r"].cumsum()  # cumulative reward over all episodes
rewards= df["r"].rolling(10).mean()

plt.plot(episodes, df["r"], label="Episode reward")
plt.plot(episodes, rewards, label="Rolling mean")
plt.xlabel("Episode")
plt.ylabel("Reward")
plt.legend()
plt.title("Training performance")
plt.show()

# Plot zero-range vehicles
plt.figure()
plt.plot(episodes, df["zero_range"], label="Zero-range vehicles (rolling)")
plt.xlabel("Episode")
plt.ylabel("Zero-range vehicles")
plt.legend()
plt.xlim(0,)
plt.ylim(0,)
plt.show()

# Plot energy consumption
plt.figure()
plt.plot(episodes, df["eff"], label="Efficiency")
plt.xlabel("Episode")
plt.ylabel("Efficiency")
plt.legend()
plt.show()

# import pandas as pd
# import matplotlib.pyplot as plt
# import os
#
# # Path to the CSV file generated by Monitor
# log_dir = "training_logs"
# monitor_file = os.path.join(log_dir, "monitor.csv")
#
# # Skip the first two lines (header info)
# with open(monitor_file, 'r') as file:
#     lines = file.readlines()[2:]
#     with open("temp_monitor_cleaned.csv", 'w') as temp_file:
#         temp_file.writelines(lines)
#
# # Now load the cleaned CSV
# df = pd.read_csv("temp_monitor_cleaned.csv")
#
# # Compute cumulative reward
# df['cumulative_reward'] = df['r'].cumsum()
#
# # Plot
# plt.figure(figsize=(10, 5))
# plt.plot(df['cumulative_reward'], label='Cumulative Reward')
# plt.xlabel('Episode')
# plt.ylabel('Cumulative Reward')
# plt.title('Cumulative Reward over Episodes')
# plt.grid(True)
# plt.legend()
# plt.tight_layout()
# plt.show()